site_name: Wiki
site_url: https://wiki.xjtlu.zone/docs/
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  palette:
    primary: white
nav:
  - 学术资料: 
    - CCT:
      - c1: 学术资料/CCT/c1.md
    - 计算机:
      - c2: 学术资料/计算机/c2.md
  - 知识科普:
    - 大脑Project:
      - test: 知识科普/大脑Project/test.md
    - 春秋历史:
      - test: 知识科普/春秋历史/test.md
    - 人工智能:
      - test: 知识科普/人工智能/test.md
    - 南斗天文:
      - test: 知识科普/南斗天文/test.md
    - 西翼航空:
      - test: 知识科普/西翼航空/test.md
    - CLCU:
      - test: 知识科普/CLCU/test.md
    - 剑术协会:
      - test: 知识科普/剑术协会/test.md
