site_name: Wiki | 知识科普
site_url: https://wiki.xjtlu.zone/docs/knowledge
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: white

extra:
  homepage: https://wiki.xjtlu.zone
